In [1]:
import pandas as pd

In [ ]:
#Colunas originais do dataset

email_col= "Email"
telefone_col= " TelefoneAjustado"
df_rd 
   email_limpo

In [3]:
arquivo = "../data/raw/BASE COMPLETA - 01.2024-09.2025.csv"
df=pd.read_csv(
    arquivo,
    sep=";",
    encoding="latin1",
)
df.head()

/var/folders/bc/8yl7z4r90w5bnr3r40t4d7qm0000gn/T/ipykernel_996/4094662564.py:2: DtypeWarning: Columns (55,59) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(

,TipoUH,UH,Localização,Pensão,Diárias,Hóspede,CidadeUF,Email,TelefoneAjustado,Telefone,...,ObservaçãoIntegração,Walkin,Tipodetarifa,Tarifario,Ticketours,VoucherEmpresa,PreCheckIn,RrnOmnibees,DataHoraPreCheckIn,AllInclusive
0,LUXOMAR,1909.0,VISTAPARCIALMAR,CafédaManha,8.0,ALEXALEGRIA,RIODEJANEIRORJ,alalegri@gmail.com,+55 56981620563,56981620563,...,IDTRAVEL:1777435IDOTA:2590131421POLITICADEPAGA...,Não,TarifaDiaaDia,NaN,NaN,NaN,N,NaN,NaN,NaN
1,LUXOCASAL,1904.0,VISTAMONTANHA,CafédaManha,4.0,ADENILSODOSPASSOSGNOATTO,MARILANDIADOSULPR,AGNOAT.952426@GUEST.BOOKING.COM,+55 43999010638,43999010638,...,Reservationextrainfo:\rFlags:booker_is_genius:...,Não,TarifaDiaaDia,NaN,NaN,NaN,N,NaN,NaN,NaN
2,LUXOCASAL,2001.0,VISTAMONTANHA,Nenhuma,7.0,ENZOPIETRORODRIGUESMORSELLI,SAOPAULOSP,NaN,+55 11963101699,11963101699,...,NaN,Não,Tarifafixa,NaN,NaN,NaN,N,NaN,NaN,NaN
3,SUÍTESEREIA,2612.0,VISTAPARCIALMAR,Nenhuma,6.0,CARLOSROGERIODOSSANTOS,VITORIAES,crogsantos@yahoo.com.br,+55 27998937669,27998937669,...,NaN,Não,Tarifafixa,NaN,NaN,NaN,N,NaN,NaN,NaN
4,LUXOCASAL,2306.0,VISTAMONTANHA,CafédaManha,8.0,FRANCOMULATERO,EXTERIOREX,FRANCOMULATERO2000@OUTLOOK.COM,0,NaN,...,IDTRAVEL:1816633CUPOM:R4045670108VALORPCTTOTAL...,Não,TarifaDiaaDia,NaN,NaN,NaN,N,NaN,NaN,NaN

In [4]:
import re #Biblioteca padrão de expressões regulares (regex)
import pandas as pd
import unicodedata #Biblioteca padrão do Python para lidar com unicode(acentos,caracteres especiais)

In [5]:
#Função para limpar nome de coluna
# re.sub (padrão, substituto, texto) "Procure um padrão dentro do texto e substitua por outra coisa"
def limpar_nome_coluna(col:str) -> str:  #Diz que a coluna é texto e que a função devolve texto
    col=str(col).strip() #Reforço que a coluna é string e uso .strip para remover espaços
    col=re.sub(r"(?<=[a-z0-9])(?=[A-Z])"," ", col) #Este é um padrão mais avançado, ele insere um espaço entre letra minúscula e número e a outra entre letra maiúscula e número. Sintaxe, r significa: raw string
    # diz, náo interprete \ como espaço " ". Lookbehind (?<=...) "verifique o que vem antes mas não consuma, A a Z e 0 a 9. Lookhead "verifique o que vem depois mas nõs consuma"[A-Z] qualquer letra maiúscula 
    # existe qualquer letra maiúscula depois?. Até esse ponto somente identificação por fim após o parenteses o re.sub fala para substituir a vírgula por espaço
    col=re.sub(r"[_\-\/]+", " ", col)  #Pega _ ou - ou/ e troca por espaço, é usada a barra invertida para remover a ambiguidade e demonstrar que aquele é só o sómbolo mesmo.
    col=re.sub(r"\s+", " ", col). strip() # \s+ significa "um ou mais espaços ou tabs" troca tudo por um espaço só

In [6]:
## 3. Padronização de texto interno (strings)
#Objetivo: Remover espaços invisíveis, múltiplos espaços e ruídos de formação sem alterar os significado dos dados
def limpar_texto(x): #X é um placeholder, indica um valor qualquer vindo de uma célula do dataframe, ele precisa existir para ser o agente da iteração, a limpeza de texto passará por todos os valores do dataframe
    if pd.isna(x): # isna mean ïs not available" se o valor não estiver disponível ele retorna Nan ou None e não limpa pois não tem valor ali 
        return x
    s= str(x) # Indicamos que a partir de agora vamos trabalhar com texto
    s=s.replace("\u00a0", " ") # Este é um caractere unicode chamado de Non-breaking space, seria trocar o espaço da máquina por um espaço normal
    s=re.sub(r"\s+"," ",s) # Isso significa qualquer sequencia de espaços várias vezes
    return s.strip() # Retorna o s limpo e o último strip garante a limpeza das bordas

In [7]:
# Nesta parte vamos criar uma lista com os nomes das colunas que contém a palavra "email", o df.columns é um index do pandas que se comporta como:
# uma lista de nomes de colunas 
print([c for c in df.columns if "Email" in c] or ("E-mail" in c))

['Email', 'EmailReservante']

In [8]:
# Tínhamos criado uma lista contendo as colunas de email, decidi trabalhar com a "Email" como coluna principal
email_col= "Email"
email_col

'Email'

In [9]:
df[email_col]=(       #Normalização de valores, estou pegando uma série do pandas que representa uma coluna inteira, o astype converte a coluna para str
   df[email_col]     # O str. garante que as ações serão aplicadas elemento por elemento. str.trip() - tira os espaços no início e no fim.  str.lower() converte tudo para min
   .astype("string")
   .str.strip()
   .str.lower()
)

In [10]:
df[email_col].head(10)
df[email_col].isna().sum

<bound method Series.sum of 0        False
1        False
2         True
3        False
4        False
         ...
47411    False
47412     True
47413    False
47414    False
47415     True
Name: Email, Length: 47416, dtype: bool>

In [13]:
#Normalização telefone
print([c for c in df.columns if "tel" in c.lower()])

['TelefoneAjustado', 'Telefone']

In [14]:
telefone_col= "TelefoneAjustado"
telefone_col

'TelefoneAjustado'

In [15]:
#Normalização de telefone
def normalizar_telefone(x):
    if pd.isna(x):
        return(x)
    
    s=str(x)
    #remove o que não é díget_ipython
    s=re.sub(r"\D", " ",s)
    return s 

df[[telefone_col]].head(10)

  TelefoneAjustado
0  +55 56981620563
1  +55 43999010638
2  +55 11963101699
3  +55 27998937669
4                0
5  +55 17996075227
6      4,47726E+11
7       7765243940
8  +55 11961959293
9       7863167796

In [16]:
df[telefone_col] = df[telefone_col].apply(normalizar_telefone)
df[telefone_col].head(10)
df[telefone_col].isna().sum()

np.int64(0)

In [17]:
df.value_counts()

Series([], Name: count, dtype: int64)

In [18]:
df[telefone_col].value_counts()

TelefoneAjustado
0                  8897
5 522  12           935
5 52199  12         798
5 52198  12         797
5 52197  12         614
                   ...
17476731315           1
 55 51991287273       1
 55 61998260700       1
 55 16981116633       1
4796502867            1
Name: count, Length: 18850, dtype: int64

In [19]:
df[email_col].value_counts()

Email
hn@hn.com                          328
h@h.com                             89
alison_nazareno@yahoo.com.br        55
ronniekosa@yahoo.com                43
priscilamartins27@yahoo.com.br      38
                                  ...
dacaozhou@gmail.com                  1
daling.wen@gmail.com                 1
diegorosendemartinez1@gmail.com      1
nalves.457418@guest.booking.com      1
bajofarias@gmail.com                 1
Name: count, Length: 29399, dtype: Int64

In [20]:
total_registros= len(df) #Primeiro definimos o tamanho da lista de total de registros
email_preenchidos = df[email_col].notna().sum() # Aqui contamos com o "notna" - "notnan" ou "notnulo" ele me da um valor booleano em que os não nulos são True e os Nulos são False
email_vazios= df[email_col].isna().sum() #Por fim contamos os que são nulos e comparamos

In [21]:
total_telefone= len(df) #Definição de quantidade de números de telefone
telefone_preenchidos= df[telefone_col].notna().sum() #Quantos espaços estão preenchidos
telefone_vazios = df[telefone_col].isna().sum() #Quantos espaços são nulos

In [22]:
ambos = df[df[email_col].notna() & df[telefone_col].notna()] # Colocar o df dentro de um parenteses maior garante que o data frame geral filtre tudo que é definifo dentro do booleano seguinte
somente_telefone= df[df[email_col].isna() & df[telefone_col].notna()] # O caractere $ é um elemento de lógica booleana vetorizada, avalia os dados linha a linha e guarda e soma 
# os resultados, apenas se a condição estabelecida for verdadeira
somente_email= df[df[email_col].notna() & df[telefone_col].isna()]

print(len(ambos))
print(len(somente_telefone))
print(len(somente_email))

38857
8559
0

In [23]:
print(df[telefone_col].nunique()) #Aqui com a função nunique nós pedimos os valores únicos de cada telefone 
print(telefone_preenchidos)

18850
47416

In [24]:
base_pessoas=( # Criei uma variável de base de pessoas e agrupei nela os telefones, em size() em groupby ele conta "para cada grupo de telefone quantas linhas existe
    df
    .groupby(telefone_col)
    .size()
    .rename("n_interacoes") 
    .reset_index()   #Todo esse processo gera uma series e não uma coluna então o reset index garante tirar o índice e criar uma coluna
)

print(base_pessoas.head())
print(base_pessoas["n_interacoes"].describe().round(2))

# O describe mostra que a média de aparições é de baixa duplicação, mostra que 75% das pessoas tem somente uma aparição o que é bem consistente, temos outliers de - std - 
# desvio padrão e no número máximo, o desvio pardão explode por ter uma ocorrência muito alta se comparada com as outras, manteremos como um dado a ser aprofundado.

       TelefoneAjustado  n_interacoes
0            2152662527             1
1           21982913379             1
2           31997488604             1
3           33675042740             1
4           56965899184             1
count    18850.00
mean         2.52
std         66.32
min          1.00
25%          1.00
50%          1.00
75%          1.00
max       8897.00
Name: n_interacoes, dtype: float64

In [25]:
# Buckets ou faixa de recorrência - Scoring - Quem são as pessoas em termos de frequência?

bins=[0,1,3,10,50, float("inf")] #O bins define o intervalo numérico e o labels define as etiquetas. O "inf" é uma garantia que nenhum valor fique de fora nem os extremos, vem de infinite
labels=[
    "1_interacao",
    "2_3_interacoes",
    "4_10_interacoes",
    "11_50_interacoes",
    "51+_interacoes"
]

base_pessoas["faixa_recorrencia"]=pd.cut( # O pd.cut é responsável por cortar a coluna contínua dentro do dataframe usando os intervalos definidos em bins e labels 
    # bins define onde cortar e labels como chamar cada pedaço. 
    base_pessoas["n_interacoes"],
    bins=bins,
    labels=labels
)

In [ ]:
##Limpeza e adequação - Email
df_rd=df.copy()

df_rd["email_limpo"]=(
    df_rd[email_col]
    .astype("string")
    .str.strip()
    .str.lower()
)

df_rd.loc[df_rd["email_limpo"] == "", "email_limpo"] = pd.NA
df_rd[[email_col, "email_limpo"]].head(10)

#Aqui criei um novo dataframe cópia do anterior, para fazer a limpeza em segurança, defini que tudo será string, isso ajuda para não termos problemas com os números, removi espaços e por fim padronizei
#tudo em minúsculo. Também transformei vazio em NA.

                             Email                      email_limpo
0               alalegri@gmail.com               alalegri@gmail.com
1  agnoat.952426@guest.booking.com  agnoat.952426@guest.booking.com
2                             <NA>                             <NA>
3          crogsantos@yahoo.com.br          crogsantos@yahoo.com.br
4   francomulatero2000@outlook.com   francomulatero2000@outlook.com
5                giba.gl@gmail.com                giba.gl@gmail.com
6  dclark.219633@guest.booking.com  dclark.219633@guest.booking.com
7  eoyenu.108827@guest.booking.com  eoyenu.108827@guest.booking.com
8                             <NA>                             <NA>
9                             <NA>                             <NA>

In [36]:
df_rd.columns
print(telefone_col)

TelefoneAjustado

In [43]:
import pandas as pd
import numpy as np

tel=(
    df_rd[telefone_col]
    .astype("string")
    .str.strip()
    .str.replace(r"\D+","", regex=True)
    .replace("", pd.NA)
)

In [48]:
def padroniza_tel_com_ddi(x):
    if pd.isna(x):
        return pd.NA
    
    if len(x) in (10,11):
        return "55" + x

    if x.startswith("55") and len(x) in (12,13):
        return x

    if 8<= len(x) <=15:
        return x

    return pd.NA

df_rd["telefone_limpo"]= tel.apply(padroniza_tel_com_ddi)

df_rd["telefone_limpo"].str[:2].value_counts(dropna=False).head(10)

telefone_limpo
55      30929
<NA>    12597
54        996
44        482
05        433
35        272
49        240
57        162
52        110
39        108
Name: count, dtype: int64

In [50]:
df_rd["chave_contato"]=df_rd["email_limpo"]
df_rd.loc[df_rd["chave_contato"].isna(), "chave_contato"] = df_rd["telefone_limpo"]

df_rd["score_completude"]= df_rd.notna().sum(axis=1)
df_rd=df_rd.sort_values(by=["chave_contato", "score_completude"], ascending=[True,False])

df_dedupe = (
    df_rd
    .dropna(subset=["chave_contato"])
    .drop_duplicates(subset=["chave_contato"], keep="first")
)

print("Antes:", len(df_rd))
print("Depois(dedupe):", len(df_dedupe))

Antes: 47416
Depois(dedupe): 32235

In [52]:
print("Linhas antes:", len(df_rd))
print("Linhas depois:", len(df_dedupe))

print("Chaves únicas:", df_dedupe["chave_contato"].nunique())

print("Sem email e sem telefone:", df_rd["chave_contato"].isna().sum())

Linhas antes: 47416
Linhas depois: 32235
Chaves únicas: 32235
Sem email e sem telefone: 4088

In [53]:
cols_keep = [
    "Hóspede",
    "email_limpo",
    "telefone_limpo",
    "CidadeUF",
    "OrigemReserva",
    "TipoUH",
    "GrupoHospedagem",
    "IdIntegração",
    "UHC",
]

cols_keep=[c for c in cols_keep if c in df_dedupe.columns]
df_export=df_dedupe[cols_keep].copy()

rename_map={
    "Hóspede":"nome",
    "CidadeUF":"cidade_uf",
    "OrigemReserva":"origem_reserva",
    "MeioComunição": "meio_comunicacao",
    "SegmentoMercado": "segmento_mercado",
    "TipoUH":"tipo_uh",
    "GrupoHospedagem":"grupo_hospedagem",
    "IdIntegração":"id_integracao"
}
df_export=df_export.rename(columns=rename_map)

In [54]:
print(df_export.isna().mean().sort_values(ascending=False).head(10))
print(df_export["telefone_limpo"].astype("string").str[:2].value_counts(dropna=False).head(15))

grupo_hospedagem    0.971553
telefone_limpo      0.211230
id_integracao       0.169443
email_limpo         0.087979
origem_reserva      0.000186
cidade_uf           0.000062
nome                0.000000
tipo_uh             0.000000
dtype: float64
telefone_limpo
55      22462
<NA>     6809
54        802
44        372
05        330
35        188
49        186
57        129
52         89
39         81
59         73
97         69
33         32
00         31
86         29
Name: count, dtype: Int64

In [56]:
df_export.to_csv("rd_base_limpa_dedupe.csv", index=False, encoding="utf-8-sig")
print("Gerado:rd_base_limpa_dedupe.csv")

Gerado:rd_base_limpa_dedupe.csv